### ISSUE TITLE
Units of cross sections

### ISSUE THREAD

**Issue by ibaris** [jleinonen/pytmatrix#13]
As far as I know, the cross sections are in units of area. But in the code the calculation of extinction cross section is
```
    2 * scatterer.wavelength * S[1,1].imag
```
which would give a unit of a length? Can you please provide the reference of this equation? This would be really nice. 

Thank you.

**Comment by jleinonen** [comment]
This equation is a consequence of the optical theorem. Note that it's only valid when the scattering geometry is set to forward scattering (as noted in the wiki documentation). You can see this in, for instance, Eqs. 13a and 13b of Chapter 16 of the book Light Scattering by _Nonspherical Particles: Theory, Measurements and Applications_ by Mishchenko et al. The PDF of the book is available here: https://www.giss.nasa.gov/staff/mmishchenko/books.html

Note that the elements of `S` are in units of length, so multiplying this by the wavelength results in a unit of area.

**Comment by ibaris** [comment]
Hello jleinonen,

thank you very much for the detailed answer and the reference. I was not aware that S also has a unit of length. 

Great work!
