### ISSUE TITLE
Conda packages seem to be out of date

### ISSUE THREAD

**Issue by josephhardinee** [jleinonen/pytmatrix#15]
It looks like the current conda package is out of date on conda-forge. It still appears to have the bug that the most recent commit fixed (scattering table IO). I'm not sure who is maintaining, but it would be good to re-issue these packages based on newest code.

**Comment by josephhardinee** [comment]
@jleinonen, If you issue a new PyPI release of this and increment version to 0.3.2 I think it should auto-update conda-forge as well.

**Comment by jleinonen** [comment]
Sorry this took so long, but I just released a new version 0.3.2 with the latest fixes and pushed it to PyPI.
