### ISSUE TITLE
Calculate Nw 

### ISSUE THREAD

**Issue by yogeshkkolte** [jleinonen/pytmatrix#16]
Do we have any function to calculate Nw if we have Median drop diameter (Do) and  reflectivity Z ?

**Comment by jleinonen** [comment]
There is no such function unfortunately. The relationship between Nw, D0 and Z depends on the drop size distribution properties. Since the Z given by T-Matrix is not an analytic function of Nw and D0, you generally need to invert it using some iterative solution.
