### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by kmuehlbauer** [jleinonen/pytmatrix#17]
- `LICENSE.txt` in source folder claims to be BSD-3-clause.
- License header in setup.py is MIT

As `LICENSE.txt` is **not** distributed with PyPI, people who install from there might assume this package is MIT, whereas people who are installing from GITHUB might assume this is BSD-3-Clause.

Now, what license should be used when redistributing this package?

**Comment by jleinonen** [comment]
I'm looking into this now. Not sure what the issue is, the license text is exactly the same in `LICENSE` and in `setup.py`: the MIT license. Where do you see the BSD license?

**Comment by kmuehlbauer** [comment]
@jleinonen I've no idea what made me issue this. There is no BSD license here. Good to know, that it's MIT license, and, sorry for the noise.
