### ISSUE TITLE
Error in drop shape relationship function

### ISSUE THREAD

**Issue by krihabu** [jleinonen/pytmatrix#19]
Hi,

there is an error, probably a typo, in the function dsr_bc() in tmatrix_aux: The factor D_eq is missing for the second summand (see for example Bringi and Chandrasekar 2001, equation 7.3).

Regards and thank you for this python interface for the T-matrix method!

**Comment by jleinonen** [comment]
Thanks for the report, sorry it took a while to implement the fix. It's now fixed in d8b199d35fed983d1deefc415a09492f63c8d588.
