### ISSUE TITLE
Roundoff error during  test_adaptive_orient

### ISSUE THREAD

**Issue by ByeonghoAhn** [jleinonen/pytmatrix#27]
Hello, 

I would like to inform you that while running "test_tmatrix.run_tests()", I have got the following warning:

----------------
test_adaptive_orient (pytmatrix.test.test_tmatrix.TMatrixTests)
Test an adaptive orientation averaging case ... C:\ProgramData\Anaconda3\lib\site-packages\scipy\integrate\quadpack.py:879: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  quad_r = quad(f, low, high, args=args, full_output=self.full_output,
C:\ProgramData\Anaconda3\lib\site-packages\scipy\integrate\quadpack.py:879: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is
  the best which can be obtained.
  quad_r = quad(f, low, high, args=args, full_output=self.full_output,
ok
-------

I reported it here, as I am not sure whether this waring is expected.

Best,
BA

**Comment by jleinonen** [comment]
Hi BA,

Thanks for the report. Does this cause the test to fail? If not, everything should be ok. I haven't seen this message before but something may have changed in the SciPy integration routines.

**Comment by ByeonghoAhn** [comment]
Hello Mr. Leinonen,

Thank you for the response. The test succeeded: I got the "ok" at the end of the warning. Okay, then I'll not worry about the error. You can close the issue. I wish you a good day.

Best,
BA
