### ISSUE TITLE
What is the limitation of this code?

### ISSUE THREAD

**Issue by limilyli** [jleinonen/pytmatrix#29]
Hello,

I'm wondering if this code is suitable for both lidar and radar to compute the scattering cross section and extinction  cross section in bad weather (such as rain, fog, and dust storms), in other words, whether this code is self-adaption for the Rayleigh scattering and Mie scattering?

Thanks a lot!

**Comment by jleinonen** [comment]
Hi @limilyli, the code can handle both Rayleigh and Mie scattering. It uses the T-matrix method for all scatterers, which includes Rayleigh and (spherical) Mie scattering as special cases.
